name: Publication

on:
    push:
        branches:
            - build

jobs:
    release:
        if: github.repository == 'Ganyu-Studios/Hoshimi'
        name: Create Release
        runs-on: ubuntu-latest
        outputs:
            version: ${{ steps.release.outputs.version }}
            created: ${{ steps.release.outputs.release_created }}
        permissions:
            contents: write
            issues: write
            pull-requests: write
        steps:
            - uses: googleapis/release-please-action@v4
              id: release
              with:
                  release-type: node

    publish:
        if: ${{ needs.release.outputs.created }}
        name: Publish Release
        needs: release
        runs-on: ubuntu-latest
        permissions:
            contents: read
            id-token: write
        steps:
            - name: Checkout
              uses: actions/checkout@v5

            - name: Setup Node
              uses: actions/setup-node@v5
              with:
                  cache: npm
                  node-version: 22
                  registry-url: https://registry.npmjs.org
                
            - uses: pnpm/action-setup@v4
              with:
                  version: 9

            - name: Update pnpm
              run: pnpm i -g pnpm@latest

            - name: Install dependencies
              run: pnpm ci

            - name: Build v${{ needs.release.outputs.version }}
              run: pnpm run build

            - name: Publish v${{ needs.release.outputs.version }}
              run: npm publish
